package io.github.huypva.helloworld.dataprovider.entity;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * @author huypva
 */
@DynamoDBTable(tableName = "Book")
@Data
@AllArgsConstructor
@NoArgsConstructor
public class Book {

  @DynamoDBHashKey
  @DynamoDBAutoGeneratedKey
  private String book_id;

  @DynamoDBAttribute
  private String name;
}
