spring:
  application:
    name: "hello-word"
aws:
  region: ap-southeast-1
  accessKey: ${AWS_ACCESS_KEY_ID}
  secretKey: ${AWS_SECRET_ACCESS_KEY}
  dynamodb:
    endpoint: https://dynamodb.ap-southeast-1.amazonaws.com